# Composer file to backend development

services:
    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    cpus: "0.25"
                    memory: 256M
        tty: true
        stdin_open: true

    backend:
        build:
            context: .
            dockerfile: Dockerfile-dev
        volumes:
            - .:/app
        ports:
            - "9000:9000"
        depends_on:
            - mongodb
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    cpus: "0.25"
                    memory: 256M
        tty: true
        stdin_open: true
        command: ["yarn", "run", "dev"]
